services:
  web:
    build: svc.web
    ports:
      - "42080:80"
    volumes:
      - data_feed:/usr/share/nginx/data:ro
    restart: always
  fetch:
    build: svc.fetch
    volumes:
      - data_feed:/data
    restart: always

volumes:
  data_feed:
